# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2026-01-04T20:11:20Z"
    generation: 1
    labels:
      app: hashgenerator-dep
    name: hashgenerator-dep
    namespace: default
    resourceVersion: "7644"
    uid: 577cfc0e-db07-455d-b5c6-829aae2a05e8
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: hashgenerator-dep
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: hashgenerator-dep
      spec:
        containers:
        - image: jakousa/dwk-app1
          imagePullPolicy: Always
          name: dwk-app1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-01-04T20:11:20Z"
      lastUpdateTime: "2026-01-04T20:12:04Z"
      message: ReplicaSet "hashgenerator-dep-54ddc5f49c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-01-05T19:17:22Z"
      lastUpdateTime: "2026-01-05T19:17:22Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2026-01-04T22:31:18Z"
    generation: 1
    labels:
      app: log-output
    name: log-output
    namespace: default
    resourceVersion: "7647"
    uid: 3c09f25b-d8fb-4bac-abff-e3f288884634
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: log-output
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: log-output
      spec:
        containers:
        - image: preciousdipe/log-output
          imagePullPolicy: Always
          name: log-output
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-01-04T22:31:18Z"
      lastUpdateTime: "2026-01-04T22:31:42Z"
      message: ReplicaSet "log-output-6cfd6c559b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-01-05T19:17:22Z"
      lastUpdateTime: "2026-01-05T19:17:22Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata: {}
